"""add grade column

Revision ID: 1d463fca5798
Revises: 497a185f55df
Create Date: 2025-04-08 07:56:04.592533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d463fca5798'
down_revision = '497a185f55df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('essays', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade', sa.String(length=50), nullable=True, comment='作文年级水平'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('essays', schema=None) as batch_op:
        batch_op.drop_column('grade')

    # ### end Alembic commands ###
