"""add subscription status and plan columns

Revision ID: 497a185f55df
Revises: 
Create Date: 2025-04-07 21:19:34.043571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '497a185f55df'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('subscription_plan_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('subscription_expires', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('essay_monthly_limit', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('essay_monthly_used', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reset_date', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key('fk_user_profiles_subscription_plan', 'membership_plans', ['subscription_plan_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_profiles_subscription_plan', type_='foreignkey')
        batch_op.drop_column('reset_date')
        batch_op.drop_column('essay_monthly_used')
        batch_op.drop_column('essay_monthly_limit')
        batch_op.drop_column('subscription_expires')
        batch_op.drop_column('subscription_plan_id')
        batch_op.drop_column('subscription_status')

    # ### end Alembic commands ###
